### ISSUE TITLE
CNAME DMARC not working

### ISSUE THREAD

**Issue by donserdal** [steffenfritz/mxcheck#29]
**Describe the bug**
When checking a domain with a CNAME'd There is a Go Panic regarding 

**To Reproduce**
Check a domain with a CNAME'd DMARC record
Can be created using: https://mxtoolbox.com/dmarc/dmarc-setup-cname

**Expected behavior**
DMARC report :-D 

**Screenshots**
 user@server:~$ mxcheck -n -s < REDACTED >.nl -S default

INFO:  2024/05/14 15:24:50 == Checking: < REDACTED >.nl ==
INFO:  2024/05/14 15:24:50 Found MX:
INFO:  2024/05/14 15:24:50          < REDACTED >-nl.mail.protection.outlook.com.
INFO:  2024/05/14 15:24:50 == Checking DKIM record ==
INFO:  2024/05/14 15:24:50 DKIM not set or wrong selector
INFO:  2024/05/14 15:24:50 == Checking DMARC record ==
panic: interface conversion: dns.RR is *dns.CNAME, not *dns.TXT

goroutine 1 [running]:
main.getDMARC({0x7fff3566f5fd?, 0xc0000c95d8?}, {0x70ad2f, 0x7})
        /home/user/go/pkg/mod/github.com/steffenfritz/mxcheck@v1.5.2/dns.go:245 +0x3cc
main.main()
        /home/user/go/pkg/mod/github.com/steffenfritz/mxcheck@v1.5.2/main.go:167 +0xd56

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by steffenfritz** [comment]
Hi,

the check is done against a TXT entry and not CNAME, This has to be handled and therefore I added the bug label.

However, in your report snipper I see "DKIM not set or wrong selector". Can you redo the test with the correct selector?

**Comment by steffenfritz** [comment]
Closed with https://github.com/steffenfritz/mxcheck/pull/54/commits/83530514f7b27c55d4d91d64b888462bd5f0ffa1 to prevent a panic
